/* table */
DROP TABLE IF EXISTS job_segments;
DROP TABLE IF EXISTS segment_jans;
DROP TABLE IF EXISTS segments RESTRICT;
DROP TABLE IF EXISTS bunrui_types RESTRICT;
DROP TABLE IF EXISTS sexes RESTRICT;
DROP TABLE IF EXISTS jobs RESTRICT;
DROP TABLE IF EXISTS report_types;
DROP TABLE IF EXISTS im_jicfs;
DROP TABLE IF EXISTS mmm RESTRICT;

/* view */
DROP VIEW IF EXISTS v_mmm;
